name: Run e2e Tests
description: Runs a set of tests within a docker container
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  environment:
    description: The environment which the tests are to be run against.
    required: true
  image:
    description: The image which contains the tests and test runner.
    required: true
outputs:
  login:
    description: The ecr login command
